version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: passwordmanager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE: passwordmanager
      MYSQL_USER: pmuser
      MYSQL_PASSWORD: StrongPass123!
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # container_name: passwordmanager-server
    restart: always
    env_file:
      - ./server/.env.docker
    expose:
      - "3001"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: passwordmanager-nginx
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
 

volumes:
  db_data:
